Add One  keyboard's sounds
Miodec/monkeytype pull request #1076
Opened 2021-03-11 10:04 UTC by MysteriousLog6

Added one  keyboard's sound , a bit busy due to exams but will be adding more over the coming weeks

2021-03-11 23:14 UTC, Miodec requested changes

2021-03-11 23:14 UTC, Miodec commented on src/js/sound.js
> +      },
These sounds are in the `4` property of sounds. It needs to be in its own property, same as its id (in this case `5`)

2021-03-12 02:45 UTC, MysteriousLog6 commented on src/js/sound.js
> +      },
Sorry about that will fix it!

2021-03-12 02:57 UTC, MysteriousLog6 commented on src/js/sound.js
> +      },
I have fixed it in the main branch of mine

2021-03-12 09:10 UTC, MysteriousLog6 commented
I have fixed it

2021-03-12 14:03 UTC, Miodec commented on src/js/commandline.js
> +        setPlaySoundOnClick("5");
Duplicate entry, also it seems like the curly brackets are messed up here

2021-03-12 14:05 UTC, Miodec commented
Also you didnt seem to fix the previous issue (or didn't push it to the remote repo)

2021-03-12 14:07 UTC, MysteriousLog6 commented
I am new to doing pull requests so I really don't know how to allow the changes requested.

2021-03-12 14:09 UTC, Miodec commented
> I am new to doing pull requests so I really don't know how to allow the changes requested.

You don't just approve them, you need to make the changes yourself and push them to your remote master branch.

2021-03-12 14:14 UTC, MysteriousLog6 commented
Well I did do that will try doing it later , windows is updating so can't do anything on my laptop.

2021-03-12 22:09 UTC, UnrealApex commented
@MysteriousLog6 

### Documentation on Pull Requests 
----
- [About Pull Requests](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests)
- [Basic Overview](https://guides.github.com/activities/hello-world/)
- [Creating a Pull Request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)
- [Github Learning Lab](https://lab.github.com/)

Hope this helps.

2021-03-16 09:00 UTC, Miodec commented
FYI there are a lot of commits unrelated to the original pull request so I cant really merge this.

2021-03-16 10:23 UTC, MysteriousLog6 commented
I will have to come back to this once my exam is gone.

2021-03-20 17:06 UTC, MysteriousLog6 commented
Removing pull request will redo after a few days (A bit busy currently).

2021-03-20 17:06 UTC, closed without merging