Update Quote German
Miodec/monkeytype pull request #1474
Opened 2021-05-27 06:50 UTC by Meimersdorfer

The quote was ugly with that kind of brackets and now it is much easier and much more common.

2021-05-29 12:35 UTC, Miodec commented on static/quotes/german.json
> +      "text": "Um halb neun griff Mr Dursley nach der Aktentasche, gab seiner Frau einen Schmatz auf die Wange und versuchte es auch bei Dudley mit einem Abschiedskuss. Der ging jedoch daneben, weil
If there are double quotes surrounding the whole text you can't just use double quotes again on their own. You have to escape the double quotes with `\`

2021-05-30 02:09 UTC, UnrealApex commented on static/quotes/german.json
> +      "text": "Um halb neun griff Mr Dursley nach der Aktentasche, gab seiner Frau einen Schmatz auf die Wange und versuchte es auch bei Dudley mit einem Abschiedskuss. Der ging jedoch daneben, weil
@Meimersdorfer 
Here's an example                            
`"text": "escaped double quote  \" ",`

2021-05-30 19:55 UTC, Meimersdorfer commented on static/quotes/german.json
> +      "text": "Um halb neun griff Mr Dursley nach der Aktentasche, gab seiner Frau einen Schmatz auf die Wange und versuchte es auch bei Dudley mit einem Abschiedskuss. Der ging jedoch daneben, weil
I don't know whether this fixed it now, but I guess I put in the \... But I am quiet not sure, could also be I changed nothing...

2021-05-30 22:17 UTC, UnrealApex requested changes
```diff
-    "Kleiner Schlingel \"
+     \"Kleiner Schlingel \"
```

2021-06-01 18:00 UTC, merged

2021-06-01 18:00 UTC, Miodec commented
![image](https://user-images.githubusercontent.com/13181393/120369745-9eba5400-c30b-11eb-828f-84f26be193e4.png)

2021-06-01 18:18 UTC, UnrealApex commented
lol