Added 25 new quotes
Miodec/monkeytype pull request #1539
Opened 2021-06-13 16:27 UTC by lucas-fine

### Description

### Checklist 
- [x] I have read the [`CODE_OF_CONDUCT.md`](https://github.com/Miodec/monkeytype/blob/master/CODE_OF_CONDUCT.md) and the [`CONTRIBUTING.md`](https://github.com/Miodec/monkeytype/blob/master/CONTRIBUTING.md)
- [x] I checked if my PR has any bugs or other issues that could reduce the stability of the project
- [x] I understand that the maintainer has the right to reject my contribution and it may not get accepted.

Resolves #

2021-06-13 18:56 UTC, Miodec requested changes
Marked all the mistakes I found as well as quotes that I don't think are good enough. Please recheck again for proper grammar as well, there might be something I missed.

2021-06-13 18:56 UTC, Miodec commented on static/quotes/english.json
> +      "id": 5543
I dont think this quote is suitable.

2021-06-13 18:56 UTC, Miodec commented on static/quotes/english.json
> +      "text": "The Industrial Revolution and its consequences have been a disaster for the human race. They have greatly increased the life-expectancy of those of us who live in “advanced” countries,
`“advanced”` replace the quotes here with `\"`

2021-06-13 18:56 UTC, Miodec commented on static/quotes/english.json
> +      "id": 5553
Im not a fan of these either, sorry.

2021-06-13 18:56 UTC, Miodec commented on static/quotes/english.json
> +      "length": 249,f
remove the `f`

2021-06-13 18:56 UTC, Miodec commented on static/quotes/english.json
> +      "id": 5557
Please remove

2021-06-13 18:56 UTC, Miodec commented on static/quotes/english.json
> +      "text": "Greetings! My name is Yang, and this is my journal. dusty maps and rumors of amazing treasures have led me here, deep under the desert.",
Capitalise `dusty`

2021-06-13 18:56 UTC, Miodec commented on static/quotes/english.json
> +      "text": "Washington, Washington, six foot eight, weighs a f***ing ton, opponents beware, opponents beware, he's coming, he's coming, he's coming",
Remove the censorship

2021-06-13 18:56 UTC, Miodec commented on static/quotes/english.json
> +    },
Remove please.

2021-06-13 18:56 UTC, Miodec commented on static/quotes/english.json
> +      "id": 5549
Too short i think

2021-06-13 18:56 UTC, Miodec commented on static/quotes/english.json
> +      "id": 5555
Please remove

2021-06-13 18:56 UTC, Miodec commented on static/quotes/english.json
> +      "id": 5547
Remove please

2021-06-14 05:16 UTC, lucas-fine commented
Made requested updates

2021-06-14 18:39 UTC, Miodec approved these changes

2021-06-14 18:39 UTC, merged