New German quotes
Miodec/monkeytype pull request #1587
Opened 2021-07-01 20:56 UTC by Meimersdorfer

As I told on Discord I added all the quotes I could find myself and the ones that were already recommended by others. 
I don't know whether it is all good now and if there are still any typos I (and word :)) missed. But if there are some I will hopefully find them while typing and then I will change them in the list. 
If the format is in any way wrong please tell me, as I am not into coding yet and don't see this stuff myself.

2021-07-02 05:06 UTC, UnrealApex requested changes
I don't know German, but syntactically everything looks ok, but the spelling of `length` is wrong for each value entry. This should be relatively easy to fix with find and replace(make sure you don't accidentally change quote or author values :) ). I suggest you take a look at [this](https://www.w3schools.com/js/js_json_syntax.asp) for JSON basic syntax reference.

2021-07-02 05:06 UTC, UnrealApex commented on static/quotes/german.json
> +			"lenght": 261,
Please fix the spelling of the `length`as the key is misspelled.
```json
"length": 0,
```

2021-07-02 05:08 UTC, UnrealApex commented on static/quotes/german.json
> +			"lenght": 261,
To reduce the likelyhood of bugs and make our lives easier, I think Monkeytype should have templates(i.e quote template, language template, theme template, etc...)

2021-07-02 08:02 UTC, Meimersdorfer commented on static/quotes/german.json
> +			"lenght": 261,
What shall I do with the templates? I don't quiet know what to do with them and don't even know what they are...

2021-07-02 17:51 UTC, UnrealApex commented on static/quotes/german.json
> +			"lenght": 261,
>  I think Monkeytype should have templates(i.e quote template, language template, theme template, etc...)

They aren't created yet. I meant I would create templates, and in the future contributors could use them to reduce any errors.

2021-07-02 17:51 UTC, UnrealApex approved these changes
Syntactically appears to be correct.

2021-07-02 19:17 UTC, Meimersdorfer commented on static/quotes/german.json
> +			"lenght": 261,
Yes, that would be quiet a nice idea. I would like that one, too. Would you do it like a template site where there are two fields for like the text and the source. I think it would be very helpfull for people like me. Also it could then be possible to have people easily take a look at the quotes and like approve them just like it is done with these pull requests.

2021-07-04 14:57 UTC, Miodec requested changes
please fix indentation

2021-07-04 14:57 UTC, Miodec commented on static/quotes/german.json
> +			"source": "",
missing source

2021-07-04 14:57 UTC, Miodec commented on static/quotes/german.json
> +			"text": "Energie ist keine Frage des Alters. Sondern die Frage ist: Wie viel Energie kreieren wir jeden Tag? Wir können es nicht dem Zufall überlassen und "hoffen", dass wir eine gute Energie habe
escape "

2021-07-04 14:57 UTC, Miodec commented on static/quotes/german.json
> +			"text": "Dein Erfolg wird zu 100% davon bestimmt, welche Glaubenssätze Du hast: Über Dich selbst, über Deine Möglichkeiten, über Geld und Wohlstand (und wie viel davon Du Deiner Meinung nach "verd
escape "

2021-07-04 14:57 UTC, Miodec commented on static/quotes/german.json
> +			"text": "",Die Welt braucht Dich und Dein Lachen. Dich und Deine positive Ausstrahlung. Dich und Deinen Drang, einen positiven Unterschied in der Welt zu machen. Dich und Dein Verlangen, das Leben
text outside brackets

2021-07-04 14:57 UTC, Miodec commented on static/quotes/german.json
> +			"text": "Den Song von Notorious BIG "More Money More Problems" habe ich bis heute nicht verstanden. Denn es ist nicht die Anwesenheit, sondern die Abwesenheit von Geld, die dafür sorgt, dass Mensc
escape "

2021-07-04 16:52 UTC, Meimersdorfer commented on static/quotes/german.json
> +			"text": "Den Song von Notorious BIG "More Money More Problems" habe ich bis heute nicht verstanden. Denn es ist nicht die Anwesenheit, sondern die Abwesenheit von Geld, die dafür sorgt, dass Mensc
I hope I got them all now.

2021-07-04 16:54 UTC, Meimersdorfer commented
I hope I got them all now...

2021-07-04 17:10 UTC, merged