fixed esc actually stopping requests on slow connections
Miodec/monkeytype pull request #1840
Opened 2021-09-12 04:08 UTC by sphhax

### Description

Added an escape button blocker much earlier in the code to prevent it stopping requests on slower connections

Closes #

#1832

2021-09-12 20:33 UTC, UnrealApex requested changes

2021-09-12 20:33 UTC, UnrealApex commented on static/index.html
> +         if (e.keyCode == 27) e.preventDefault();
`event.keyCode` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode). Use `event.key` instead.

2021-09-12 20:51 UTC, sphhax commented on static/index.html
> +         if (e.keyCode == 27) e.preventDefault();
done

2021-09-13 14:45 UTC, Miodec approved these changes

2021-09-13 14:45 UTC, merged