fix for poetry funbox word limit
Miodec/monkeytype pull request #1882
Opened 2021-09-18 16:48 UTC by codeiiz

### Description

Checks if the mode is words and changes maxWords to the current word limit
Closes #1721

2021-09-18 23:12 UTC, Miodec commented
Is this at all tested? It break the website completely

2021-09-21 05:29 UTC, UnrealApex requested changes

2021-09-21 05:29 UTC, UnrealApex commented on src/js/test/poetry.js
> +import Config from './config';
Put the import statement at the top of the file.

2021-09-21 05:29 UTC, UnrealApex commented on src/js/test/poetry.js
> +if (Config.mode === "words") {
Use a ternary operator here:
```javascript
maxWords = (Config.mode === "words" ? Config.words : maxWords);
```

2021-09-21 05:29 UTC, UnrealApex commented on src/js/test/poetry.js
> +import Config from './config';
Import everything from config module:
```javascript
import * as Config from './config';
```

2021-11-20 20:04 UTC, Miodec commented
Closed by #2069

2021-11-20 20:04 UTC, closed without merging