Added some English quotes
Miodec/monkeytype pull request #2207
Opened 2021-12-25 02:10 UTC by xia0

### Description

Closes #

2021-12-26 08:05 UTC, UnrealApex requested changes
You are missing the quote `length`(how long in characters each quote is) property in the entries you have added.

2021-12-26 08:37 UTC, xia0 commented
> You are missing the quote `length`(how long in characters each quote is) property in the entries you have added.

Thanks for the heads up.

2021-12-27 12:15 UTC, Miodec approved these changes

2021-12-27 12:16 UTC, Miodec approved these changes

2021-12-27 12:16 UTC, merged