Add Desert Oasis 🏜
Miodec/monkeytype pull request #2268
Opened 2022-01-06 23:38 UTC by CaptainRex-501st

### Description

I added a theme that is supposed to look like a desert oasis (beige/yellow for sand, blues for water, and greens for palm tree leaves). In the images the menu buttons are blue but they have been coded look like the error green. Also a big thanks to TeddiNotTeddy for helping me code my first ever theme!

![unknown](https://user-images.githubusercontent.com/64493211/148467384-27a33771-78d7-41bf-a08c-0494f3910f3b.png)
![unknown](https://user-images.githubusercontent.com/64493211/148467466-938eda1f-1bef-439c-ae94-351e69759505.png)

2022-01-07 17:10 UTC, Miodec commented
Text color needs to be as close to white or black as possible. It can have a little bit of color in it, but mainly monochrome.

2022-01-08 02:56 UTC, CaptainRex-501st commented
I have changed the text color to be darker

![image](https://user-images.githubusercontent.com/64493211/148629041-7e1150ac-3976-49d3-a990-40bc326bfcb0.png)

2022-01-09 07:06 UTC, rizwanmustafa commented
This seems like a fun theme. Can't wait to try it!

2022-01-10 15:40 UTC, rizwanmustafa requested changes
Rename the theme file to "desert_oasis.css"
Will maintain consistency and prevent any errors

2022-01-10 16:04 UTC, Miodec commented on static/themes/_list.json
> +     "name": "Desert Oasis",
Also change the .css file name to all lowercase letters.

2022-01-10 17:19 UTC, CaptainRex-501st commented on static/themes/_list.json
> +     "name": "Desert Oasis",
Ok, done! Anything else I need to change?

2022-01-10 19:26 UTC, teddinotteddy approved these changes
Looks good.

2022-01-11 05:55 UTC, rizwanmustafa commented on static/themes/_list.json
> +     "name": "Desert Oasis",
Looks great.

2022-01-11 05:56 UTC, rizwanmustafa commented on static/themes/_list.json
> +     "name": "Desert Oasis",
@Miodec. please approve.

2022-01-11 17:49 UTC, merged