Added GMK trackday-based theme
Miodec/monkeytype pull request #2302
Opened 2022-01-14 23:39 UTC by batsoup804

Here's a few photos!
![image](https://user-images.githubusercontent.com/83473782/149598434-a08e078a-1a1b-497a-a634-e4c47ce717e1.png)
![image](https://user-images.githubusercontent.com/83473782/149598461-7a9dd61a-5370-47f4-9562-6868eec94cf9.png)

### Description

This PR adds the trackday theme. It's based off of the pre-production set GMK trackday, featured on novelkeys.com. I love this set so much I joined the group already but I realized how much I want this in Monkeytype so I decided to add it.
https://novelkeys.com/products/gmk-trackday
feel free to check it out:)

2022-01-15 11:24 UTC, Nugget1308 commented
Looks pretty nice, but can you use a brighter red?

2022-01-15 12:59 UTC, rizwanmustafa requested changes

2022-01-15 12:59 UTC, rizwanmustafa commented on static/themes/_list.json
> +    "bgColor": "#464d66"
Add a comma at the end of this line.

2022-01-15 23:36 UTC, batsoup804 commented on static/themes/_list.json
> +    "bgColor": "#464d66"
thanks, didnt realize there was a syntax error.

2022-01-15 23:39 UTC, batsoup804 commented
> Looks pretty nice, but can you use a brighter red?

Well the set itself uses an almost brown so I think it's fine the way it is. Besides the only person's concern about the colors I really care about is Miodec's.

2022-01-17 18:59 UTC, Miodec approved these changes
Thanks

2022-01-17 18:59 UTC, merged