Feat:Update response structure
Miodec/monkeytype pull request #2427
Opened 2022-02-07 07:46 UTC by Mustafiz04

### Here is short description what I have done in this PR
* Create a MonkeyResponse class that build response structure.
* instead of return res.status(code).json({}) from controllers now we are using return new MonkeyResponse(statusCode, message, data)
* Return both message and data in case of GET route and only message in all other case.

2022-02-07 12:34 UTC, Miodec requested changes
Replace all 200 responses:
 - `Get * successfully` - `* retrieved`
 - `* updated successfully` - `* updated`
 - `* added successfully` - `* added`

2022-02-07 12:34 UTC, Miodec commented on backend/api/controllers/leaderboards.js
> +      throw new MonkeyError(400, "Missing user id.");
Remove. This will be handled by the auth middleware.

2022-02-07 12:34 UTC, Miodec commented on backend/api/controllers/config.js
> +    return new MonkeyResponse(200, "Configuration updated successfully");
Rename `Configuration` to `Config`

2022-02-07 12:34 UTC, Miodec commented on backend/api/controllers/leaderboards.js
> +    };
I think there is a `LeaderboardsDAO` call missing here.

2022-02-07 12:34 UTC, Miodec commented on backend/api/controllers/new-quotes.js
> +    return new MonkeyResponse(200, "New quotes added successfully");
Rename `quotes` to `quote`

2022-02-07 12:34 UTC, Miodec commented on backend/api/controllers/preset.js
> +    return new MonkeyResponse(200, "Get present successfully", data);
`present` to `preset`

2022-02-07 12:34 UTC, Miodec commented on backend/api/controllers/result.js
> +    return new MonkeyResponse(200, "Result tag updated successfully");
Rename `tag` to `tags`

2022-02-07 12:34 UTC, Miodec commented on backend/middlewares/api-utils.js
> +
Move to its own file in `handlers/response`

2022-02-07 14:15 UTC, Bruception commented
This cannot get merged until we update the frontend client code.

2022-02-07 14:25 UTC, Miodec commented
> This cannot get merged until we update the frontend client code.

Yeap, also true.

2022-02-07 15:11 UTC, Mustafiz04 commented
> This cannot get merged until we update the frontend client code.
Sure

2022-02-07 15:21 UTC, Bruception commented on backend/api/controllers/result.js
> +    return new MonkeyResponse(200, "Result updated", data);
Result updated -> Result saved

2022-02-07 15:25 UTC, Bruception commented on backend/handlers/response.js
> +  var resBody = response.encryptedBody || response.body || {};
var -> const

2022-02-07 15:29 UTC, Bruception commented on backend/handlers/response.js
> +    [301, 302].indexOf(status) > -1 ? _redirectResponse : _sendResponse;
We should try to include some logic on whether or not we want to proceed with the next handler in the middleware chain. Maybe in the future we want to include additional middleware after asyncHandler.

2022-02-07 15:36 UTC, Bruception commented on backend/api/controllers/user.js
> +    return new MonkeyResponse(200, "Discord account dilinked ");
dilinked -> unlinked

2022-02-07 15:36 UTC, Bruception commented on backend/api/controllers/user.js
> +        "PTag name invalid. Name cannot contain special characters or more than 16 characters. Can include _ . and -"
PTag -> tag

2022-02-07 18:42 UTC, Bruception commented on backend/handlers/response.js
> +  constructor(status, message, data) {
Update this ordering:

`constructor(message, data, status = 200)`

2022-02-08 11:13 UTC, Mustafiz04 commented on backend/handlers/response.js
> +    [301, 302].indexOf(status) > -1 ? _redirectResponse : _sendResponse;
This will handle what you are concern with.

2022-02-08 11:59 UTC, Miodec commented
> Replace all 200 responses:
> 
> * `Get * successfully` - `* retrieved`
> * `* updated successfully` - `* updated`
> * `* added successfully` - `* added`

Some messages still dont follow this schema

2022-02-08 14:01 UTC, Bruception commented on backend/api/controllers/user.js
> +    if (!isTagPresetNameValid(tagName))
This was removed because validation happens outside of the handler.

2022-02-08 14:03 UTC, Bruception commented on backend/api/controllers/leaderboards.js
> +    return new MonkeyResponse(
Argument order needs to be changed.

2022-02-08 14:05 UTC, Bruception commented on backend/api/controllers/quotes.js
> +const { MonkeyResponse } = require("../../middlewares/api-utils");
I think this import is incorrect.

2022-02-08 14:08 UTC, Bruception commented on backend/handlers/response.js
> +  let resBody = response.encryptedBody || response.body || {};
let -> const

2022-02-08 14:14 UTC, Bruception commented
Looking forward for this to get merged. Just some minor changes along with changes suggested by @Miodec 
Could you change the PR to get merged into the branch `api-overhaul` instead of master. We will be using that branch to update the frontend client code.

2022-02-10 06:14 UTC, Mustafiz04 commented
Yes will update by today.

2022-02-10 06:15 UTC, Mustafiz04 commented on backend/handlers/response.js
> +  let resBody = response.encryptedBody || response.body || {};
can't because I update resBody at line 22 in case of error.

2022-02-10 06:25 UTC, Mustafiz04 commented
Which one ? I think all are fixed.

> > Replace all 200 responses:
> > 
> > * `Get * successfully` - `* retrieved`
> > * `* updated successfully` - `* updated`
> > * `* added successfully` - `* added`
> 
> Some messages still dont follow this schema

2022-02-10 18:30 UTC, Bruception commented on backend/api/controllers/new-quotes.js
> +    return new MonkeyResponse("New quote added successfully");
Quote submission added

2022-02-10 18:30 UTC, Bruception commented on backend/api/controllers/new-quotes.js
> +    return new MonkeyResponse("Quotes approved successfully");
Quote approved

2022-02-10 18:30 UTC, Bruception commented on backend/api/controllers/new-quotes.js
> +    return new MonkeyResponse("Quotes refused successfully");
Quote refused

2022-02-10 18:31 UTC, Bruception commented on backend/api/controllers/user.js
> +    return new MonkeyResponse("Name validated");
Username available

2022-02-10 18:32 UTC, Bruception commented on backend/api/controllers/user.js
> +    return new MonkeyResponse("User retrieved", userInfo);
User data retrieved

2022-02-10 18:50 UTC, Bruception commented
LGTM IIW

2022-02-11 11:22 UTC, Mustafiz04 commented
So ready to merge ?

2022-02-11 12:47 UTC, Bruception commented
I think so, need to wait for @Miodec input.

2022-02-12 20:09 UTC, merged