Language documentation
Miodec/monkeytype pull request #2467
Opened 2022-02-10 23:08 UTC by teddinotteddy

Added documentation for adding themes. I also made a couple of changes to the theme documentation file. I used the THEMES.md file as a template so if anything is off or I didn't cover something let me know. I am not super familiar with adding languages so it may not be perfect.

2022-02-11 16:49 UTC, rizwanmustafa requested changes
Some grammatical errors, typos and improvements.

2022-02-11 16:49 UTC, rizwanmustafa commented on LANGUAGES.md
> +First you will have ot cpoy the repostiriy also known as forking. Go to the [Monkeytype Repo](https://github.com/Miodec/monkeytype/) and then click the "fork" button.
"have to copy the repository"

2022-02-11 16:49 UTC, rizwanmustafa commented on LANGUAGES.md
> +Once you have forked the repository you can now add your langauge. (If you haven't already forked the repository yet efer to [here](#forking-the-repository).) Create a file in ```./frontend/static/la
"If you haven't already forked the repository, refer to this [section](#forking-the-repository)" is better in my opinion.

Also replace "Name it the whatever language you are adding and add the amount of words at the end" with "Create a json file with the language name and the amount of words. e.g ```language_1k.json```"

2022-02-11 16:49 UTC, rizwanmustafa commented on LANGUAGES.md
> +(I recommend that you familiarize yourself with JSON before implementing your langauge in Monkeytype.) For the name varible put the name of your language. Left to right indicates how the language is
Replace "I recommend that you familiarize yourself" with "It is recommended that you familiarize yourselves with JSON before adding a language "

2022-02-11 16:51 UTC, rizwanmustafa commented
There are a few important things that are being addressed in the codebase. I am sure Miodec will look into this PR once the problems are addressed.

2022-02-11 21:56 UTC, teddinotteddy commented
@rizwanmustafa I appreciate your help!

2022-02-13 15:32 UTC, Miodec approved these changes
Thanks

2022-02-13 15:33 UTC, merged