Ape migration p2
Miodec/monkeytype pull request #2522
Opened 2022-02-17 19:49 UTC by Bruception

### Description

- Migrated the leaderboards endpoints to use ape.

2022-02-17 20:41 UTC, Miodec approved these changes

2022-02-18 10:59 UTC, Miodec requested changes

2022-02-18 10:59 UTC, Miodec commented on frontend/src/scripts/elements/leaderboards.ts
> +    );
return here so the rest of the leaderboard loading doesn't cotinue.

2022-02-18 14:22 UTC, Bruception commented on frontend/src/scripts/elements/leaderboards.ts
> +    );
Missed this, thanks.

2022-02-18 14:43 UTC, merged