Add layout colemak_ix
Miodec/monkeytype pull request #2538
Opened 2022-02-19 14:03 UTC by starryturtle

### Description

layout colemak_ix is added

2022-02-19 14:58 UTC, Miodec commented
Please fix JSON errors: https://github.com/Miodec/monkeytype/runs/5259162893?check_suite_focus=true

2022-02-20 01:50 UTC, starryturtle commented
fixed, sorry for not being careful

2022-02-20 03:36 UTC, starryturtle reviewed
fixed

2022-02-20 12:22 UTC, Miodec requested changes

2022-02-20 12:22 UTC, Miodec commented on frontend/static/layouts/_list.json
> +      "row2": ["qQ", "lL", "cC", "mM", "kK", "jJ", "fF", "uU", "yY", ",<;:", "-_", "]}", "\\|"],
Row 2 one of the keys exceeds the maximum of 2 characters.

2022-02-20 18:36 UTC, Bruception commented on frontend/static/layouts/_list.json
>    }
This needs to be indented.

2022-02-21 03:14 UTC, closed without merging