Some Config Validation Fixes
Miodec/monkeytype pull request #2558
Opened 2022-02-22 01:36 UTC by Ferotiq

### Description

This PR does the following: 
 - allows for between 2 and 5 layouts for custom layoutfluid,
 - makes `isConfigValueValid` asynchronous.
 - makes all set functions asynchronous.
 - moves custom layoutfluid layout validation to the `isConfigValueValid` function.
 - makes an asynchronous `some` function for the `isConfigValueValid` function.
 - removes all `undefined` and `null` checks from the set functions because that's handled by the validator and `undefined` cannot be passed into the set functions (in ts anyway) due to the parameters not having undefined as an option. The `apply` function automatically assigns default values for missing properties.
 - Fixes spelling errors.

Closes #2557

2022-02-23 12:43 UTC, Miodec commented
![image](https://user-images.githubusercontent.com/13181393/155321525-5bab6610-7eac-470f-b4aa-7274c6283076.png)

Getting conflicting messages on layout fluid save (error and success at the same time).

Also we need a different error for when one of the layouts is incorrect (colema). Currently the error message is misleading.

2022-02-23 17:32 UTC, Ferotiq commented
There's a high chance this commit doesn't work yet. I'll have to correct it when I get home.

2022-02-24 03:49 UTC, Ferotiq commented
Should all be fixed by this last commit

2022-02-24 12:24 UTC, Miodec commented
Still getting an error message, the gray notice disappears too quickly to read fully 
![image](https://user-images.githubusercontent.com/13181393/155523374-ed519c1c-71c7-4336-a547-cfc50c9945d8.png)

2022-02-25 18:42 UTC, Miodec commented
Cant open custom theme color picker tab.

2022-02-26 12:03 UTC, Miodec requested changes
I think config validation is becoming quite large, lets move it to its own file.

2022-02-26 12:06 UTC, Miodec commented on frontend/src/scripts/config.ts
>    }
These lines are not needed with the cofig validation, correct?

2022-02-26 12:07 UTC, Miodec commented on frontend/src/scripts/config.ts
>    config.stopOnError = soe;
Remove boolean

2022-02-26 12:09 UTC, Miodec commented on frontend/src/scripts/config.ts
>    }
Remove boolean

2022-02-26 12:09 UTC, Miodec commented on frontend/src/scripts/config.ts
>    }
Remove boolean

2022-02-26 12:12 UTC, Miodec commented on frontend/src/scripts/config.ts
> +    return invalid("", name);
Missing first parameter?

2022-02-26 12:13 UTC, Miodec commented on frontend/src/scripts/config.ts
> +    return invalid("", theme);
Im starting to think this is intended.

2022-02-26 12:13 UTC, Miodec commented on frontend/src/scripts/config.ts
>    }
Remove bool

2022-02-26 12:15 UTC, Miodec reviewed
Also, cant we combine `isConfigValueValid` and `invalid` into one function?

2022-02-26 16:27 UTC, Ferotiq commented on frontend/src/scripts/config.ts
> +    return invalid("", mode);
lol

2022-02-26 16:28 UTC, Ferotiq commented on frontend/src/scripts/config.ts
>    config.stopOnError = soe;
> Also, cant we combine `isConfigValueValid` and `invalid` into one function?

we could

2022-02-26 21:12 UTC, merged