Add ability to store multiple custom themes
Miodec/monkeytype pull request #2589
Opened 2022-02-25 15:44 UTC by rizwanmustafa

I have done testing on my side. But I request @Miodec  to test this PR and report any bugs found before merging it. More testing is always better.

2022-02-25 16:02 UTC, Bruception commented on frontend/src/scripts/ape/endpoints/users.ts
> +  // async function getCustomThemes(): Ape.EndpointData {
Why is this commented out?

2022-02-25 16:04 UTC, Bruception commented on frontend/src/scripts/elements/commandline-lists.ts
> +  console.log("we are here");
Remove these debug console logs

2022-02-25 16:04 UTC, Bruception commented on frontend/src/scripts/elements/commandline-lists.ts
> +        console.log("asdfaasd");
^

2022-02-25 16:08 UTC, rizwanmustafa commented on frontend/src/scripts/elements/commandline-lists.ts
> +  console.log("we are here");
lol. I was supposed to remove them. Thanks for the catch.

2022-02-25 16:10 UTC, Bruception commented on backend/api/controllers/user.js
> +    try {
Remove these try catches. Any errors will be handled by the asyncHandler middleware.

2022-02-25 16:11 UTC, Bruception commented on backend/api/controllers/user.js
> +      if (customThemes === undefined) customThemes = [];
I prefer to do a falsely check rather than explicitly undefined.

2022-02-25 16:12 UTC, Bruception commented on backend/dao/user.js
> +    let _id = new ObjectId();
Const

2022-02-25 16:12 UTC, Ferotiq commented on backend/api/controllers/user.js
> +      if (customThemes === undefined) customThemes = [];
I think it’s better to do undefined checks lol

2022-02-25 16:15 UTC, Ferotiq commented on backend/api/controllers/user.js
> +      if (customThemes === undefined) customThemes = [];
does getThemes return null?

2022-02-25 16:15 UTC, Bruception commented on backend/api/controllers/user.js
> +      if (customThemes === undefined) customThemes = [];
It can. We should use this: https://lodash.com/docs/#isNil

2022-02-25 16:16 UTC, Ferotiq commented on backend/api/controllers/user.js
> +      if (customThemes === undefined) customThemes = [];
it would probably work better to do nullish coalescent and then use const in that scenario too if customThemes is never reassigned after that.

2022-02-25 16:19 UTC, Bruception commented on frontend/src/scripts/ape/endpoints/users.ts
>      const payload = newTheme;
Since we opted for partial, we should explicitly select what values we want from the custom theme argument. Since technically someone can pass _id, which would result in failed validation.

2022-02-25 16:20 UTC, Bruception commented on frontend/src/scripts/ape/endpoints/users.ts
> +  // async function getCustomThemes(): Ape.EndpointData {
Ah just leave it there, it’s okay to uncomment it.

2022-02-25 16:22 UTC, Bruception commented on backend/api/controllers/user.js
> +    return new MonkeyResponse("Custom theme succesfully updated!");
I like the enthusiasm. But we should keep these respond messages consistent with the rest of the api. Remove successfully and any full stops.

2022-02-25 16:28 UTC, Bruception commented on backend/api/controllers/user.js
> +    return new MonkeyResponse("", customThemes);
Custom themes retrieved

2022-02-25 16:29 UTC, Bruception commented on backend/api/controllers/user.js
> +    let addedTheme = await UsersDAO.addTheme(uid, customTheme);
const

2022-02-25 16:30 UTC, Bruception commented on backend/api/routes/users.ts
> +      themeID: joi
themeID -> themeId

2022-02-25 16:44 UTC, Bruception commented on backend/api/routes/users.ts
> +      colors: joi
Also this schema and others are repeated. I think it would be better to define these schemas at the top of the file and reuse them.

2022-02-25 16:48 UTC, Bruception commented on backend/dao/user.js
> +    if (user.customThemes !== undefined) {
We can do something similar here like we did in the controller file.

2022-02-25 16:48 UTC, Bruception commented on backend/dao/user.js
> +      user.customThemes === undefined ||
^

2022-02-25 16:48 UTC, Bruception commented on backend/dao/user.js
> +      user.customThemes.filter((t) => t._id == _id).length === 0
Strict equality

2022-02-25 16:49 UTC, Bruception commented on backend/dao/user.js
> +      user.customThemes.filter((t) => t._id == _id).length === 0
Strict equality

2022-02-25 17:09 UTC, rizwanmustafa commented
Please do not merge this PR as of yet. Some code quality fixes are on the way.

2022-02-25 17:09 UTC, Bruception commented
> Please do not merge this PR as of yet. Some code quality fixes are on the way.

Mark as Draft just in case.

2022-02-25 18:52 UTC, Miodec commented
`customThemeIndex` should probably be `customThemeId` because the index will change if you remove a theme.

2022-02-26 01:06 UTC, rizwanmustafa commented
> `customThemeIndex` should probably be `customThemeId` because the index will change if you remove a theme.

In case a custom theme is removed, we fallback to the first custom theme if we have one, else we fallback to presets.

2022-02-26 03:42 UTC, Ferotiq commented
My test seems to work just fine 👍

2022-02-26 11:34 UTC, rizwanmustafa commented
Need to work on hiding this issue for people without account.

2022-02-27 21:15 UTC, Bruception commented on backend/dao/user.js
> +      (user.customThemes ?? []).filter((t) => t._id.toString() === _id)
This logic is duplicated in line 392. Maybe make it a function.

2022-03-01 11:36 UTC, Miodec requested changes

2022-03-01 11:36 UTC, Miodec commented on backend/api/routes/users.ts
> +router.put(
Change to `patch`

2022-03-01 11:36 UTC, Miodec commented on frontend/src/scripts/ape/endpoints/users.ts
> +    return await apeClient.put(`${BASE_PATH}/customThemes`, { payload });
`patch`

2022-03-01 13:31 UTC, rizwanmustafa commented
Converted to draft, because I am going to work on adding the custom theme field in the config

2022-03-01 21:17 UTC, Bruception commented on backend/middlewares/rate-limit.ts
> +  windowMs: 60 * 60 * 1000, // 60 min
Change these to use the ONE_HOUR constant.

2022-03-02 11:16 UTC, rizwanmustafa commented
Added backward compatibility.

2022-03-04 09:16 UTC, rizwanmustafa commented
It's time to drive the bugs (if any) out of this PR and yeet it into master.

2022-03-07 12:37 UTC, rizwanmustafa commented
All the features are there, the only thing remaining is to test them out.

2022-03-09 12:23 UTC, rizwanmustafa commented
Succeeded by PR: #2660

2022-03-09 13:07 UTC, Miodec commented
Replaced by #2660. For some reason i couldn't push to this pr.

2022-03-09 13:07 UTC, closed without merging