Added Quotes Documentation
Miodec/monkeytype pull request #2722
Opened 2022-03-17 17:11 UTC by teddinotteddy

Added some quotes documentation. This might have some mistakes so please do let me know if you find anything.

2022-03-17 20:51 UTC, Miodec requested changes

2022-03-17 20:51 UTC, Miodec commented on QUOTES.md
> +## Theme Guidelines
theme?

2022-03-17 20:51 UTC, Miodec commented
Also please link to this new file in contributing.md

2022-03-18 15:36 UTC, teddinotteddy commented
@Miodec Alright, made those changes.

2022-03-19 14:27 UTC, Miodec approved these changes

2022-03-19 14:27 UTC, merged