Moved firebase to new version modular 9 sdk
Miodec/monkeytype pull request #2727
Opened 2022-03-17 23:49 UTC by Miodec

This gives us proper types for all firebase things and allows for tree shaking of the firebase code to reduce bundle size further

2022-03-18 00:41 UTC, Bruception requested changes
no

2022-03-18 01:40 UTC, Bruception commented on CONTRIBUTING.md
> +1. Within the `frontend/src/scripts/constants` directory, duplicate `firebase-config-example.ts`, rename it to `firebase-config.ts` and paste in your firebase config
Need to add step to create app, by default no apps are shown.

2022-03-18 01:41 UTC, Bruception commented on frontend/src/scripts/constants/firebase-config-example.ts
> +// scroll down to Your apps > Web Apps > SDK setup and configuration > select npm
Need to update these instructions

2022-03-18 12:34 UTC, Miodec commented on frontend/src/scripts/constants/firebase-config-example.ts
> +// scroll down to Your apps > Web Apps > SDK setup and configuration > select npm
Done

2022-03-18 12:34 UTC, Miodec commented on CONTRIBUTING.md
> +1. Within the `frontend/src/scripts/constants` directory, duplicate `firebase-config-example.ts`, rename it to `firebase-config.ts` and paste in your firebase config
Done

2022-03-18 14:41 UTC, Miodec commented on frontend/package.json
> +    "firebase": "9.6.0",
:)

2022-03-18 16:09 UTC, Bruception approved these changes
LGTM IIW

2022-03-19 10:57 UTC, rizwanmustafa commented on frontend/src/scripts/controllers/account-controller.js
> +const authListener = Auth.onAuthStateChanged(async function (user) {
import onAuthStateChanged directly from firebase/auth

2022-03-19 10:59 UTC, rizwanmustafa commented on frontend/src/scripts/controllers/account-controller.js
> +const authListener = Auth.onAuthStateChanged(async function (user) {
Also you can import `getAuth` from `firebase/auth` and initiate an object from which you can get the current user and pass that initiated object to the onAuthStateChanged imported from the `firebase/auth`

2022-03-19 11:03 UTC, rizwanmustafa commented on .gitignore
> +frontend/src/scripts/constants/firebase-config.ts
You can move this under the Firebase section in the top of the file.

2022-03-19 11:13 UTC, rizwanmustafa commented on frontend/src/scripts/controllers/account-controller.js
> +  setPersistence(Auth, persistence).then(function () {
Can we convert the signIn function to async function. This will get rid of the callbacks and make the code more readable.

2022-03-19 11:17 UTC, Miodec commented on frontend/src/scripts/controllers/account-controller.js
> +  setPersistence(Auth, persistence).then(function () {
After this and #2731

2022-03-19 11:22 UTC, rizwanmustafa commented on frontend/src/scripts/db.ts
>    if (user == null) return false;
Strict equality please

2022-03-19 11:25 UTC, rizwanmustafa commented on frontend/src/scripts/test/result.ts
> +    if (Auth.currentUser == null) {
Strict equality please and change to !Auth.currentUser

2022-03-19 11:25 UTC, rizwanmustafa commented on frontend/src/scripts/popups/simple-popups.ts
> +      if (user === null) return;
Please change all these `user === null` calls to `!user`. It is simpler

2022-03-19 11:33 UTC, merged