Convert chart-controller to TypeScript
Miodec/monkeytype pull request #2741
Opened 2022-03-21 00:01 UTC by DanGonite57

### Description

Convert chart-controller to TypeScript.

Continues from #2735 

Pending https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59357

Part of #2431

2022-03-21 22:21 UTC, Ferotiq commented
https://www.npmjs.com/package/@types/chartjs-plugin-trendline

2022-03-21 23:04 UTC, Bruception commented on frontend/package-lock.json
> -    "node_modules/bindings": {
This is no good.

2022-03-21 23:04 UTC, Bruception requested changes
Merge was incorrect. Please fix

2022-03-23 12:57 UTC, DanGonite57 commented
Pending merge of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59391

2022-03-23 16:12 UTC, Miodec commented on frontend/src/scripts/test/result.ts
> +  ChartController.result.updateColors();
Please bring back the +5

2022-03-23 21:58 UTC, Miodec requested changes
Those updates were removed because there were being called all at once for no reason - they were moved to `result.ts:631`

Other than that looks ok to me, but ill wait for another review from the boys that know more about typescript

2022-03-23 21:58 UTC, Miodec commented on frontend/src/scripts/test/result.ts
> +  ChartController.result.updateColors();
Please remove

2022-03-23 21:58 UTC, Miodec commented on frontend/src/scripts/test/result.ts
> +  ChartController.result.updateColors();
Another merge error

2022-03-23 22:08 UTC, DanGonite57 commented on frontend/src/scripts/test/result.ts
> +  ChartController.result.updateColors();
Fixed

2022-03-23 22:08 UTC, DanGonite57 commented on frontend/src/scripts/test/result.ts
> +  ChartController.result.updateColors();
Fixed

2022-03-24 13:12 UTC, Ferotiq commented on frontend/src/scripts/types/types.d.ts
> +    x: number;
use interfaces

2022-03-24 15:51 UTC, DanGonite57 commented on frontend/src/scripts/types/types.d.ts
> +    x: number;
Fixed

2022-03-24 18:38 UTC, Miodec approved these changes

2022-03-24 18:39 UTC, merged