DDLC quotes
Miodec/monkeytype pull request #2759
Opened 2022-03-23 23:18 UTC by WoahItsKarma

Added quotes from Doki Doki Literature Club!

2022-03-24 12:42 UTC, Miodec requested changes
Please replace all the new lines with spaces.

2022-03-25 12:20 UTC, Miodec submitted a review, later dismissed

2022-03-25 12:38 UTC, Miodec commented
The build failed, please verify the JSON structure

2022-03-26 15:55 UTC, Bruception commented
Still failing

2022-04-07 01:20 UTC, rizwanmustafa requested changes
Incorrect quote lengths.

2022-04-07 01:20 UTC, rizwanmustafa commented on frontend/static/quotes/english.json
> +      "length": 898,
```suggestion
      "length": 896,
```

2022-04-07 01:20 UTC, rizwanmustafa commented on frontend/static/quotes/english.json
> +      "length": 1160,
```suggestion
      "length": 1157,
```

2022-04-07 01:20 UTC, rizwanmustafa commented on frontend/static/quotes/english.json
> +      "length": 1062,
```suggestion
      "length": 1074,
```

2022-04-07 01:20 UTC, rizwanmustafa commented on frontend/static/quotes/english.json
> +      "length": 792,
```suggestion
      "length": 788,
```

2022-04-07 01:20 UTC, rizwanmustafa commented on frontend/static/quotes/english.json
> +      "length": 958,
```suggestion
      "length": 952,
```

2022-04-07 01:20 UTC, rizwanmustafa commented on frontend/static/quotes/english.json
> +      "length": 133,
```suggestion
      "length": 140,
```

2022-04-07 01:20 UTC, rizwanmustafa commented on frontend/static/quotes/english.json
> +      "length": 1582,
```suggestion
      "length": 1578,
```

2022-04-07 01:20 UTC, rizwanmustafa commented on frontend/static/quotes/english.json
> +      "length": 404,
```suggestion
      "length": 402,
```

2022-04-07 01:20 UTC, rizwanmustafa commented on frontend/static/quotes/english.json
> +      "length": 439,
```suggestion
      "length": 492,
```

2022-04-07 01:20 UTC, rizwanmustafa commented on frontend/static/quotes/english.json
> +      "length": 1140,
```suggestion
      "length": 1133,
```

2022-04-07 01:20 UTC, rizwanmustafa commented on frontend/static/quotes/english.json
> +      "length": 370,
```suggestion
      "length": 377,
```

2022-04-07 12:18 UTC, closed without merging