Add path aliases
Miodec/monkeytype pull request #2766
Opened 2022-03-24 23:00 UTC by Ferotiq

### Description

In this pr I replace all the relative imports with aliases that look nice.

Closes #

2022-03-25 03:08 UTC, Bruception commented
Save exact

2022-03-25 03:10 UTC, Bruception commented on package.json
> +    "eslint-import-resolver-typescript": "^2.7.0",
Save exacf

2022-03-25 03:16 UTC, Bruception requested changes
I think there might be a simpler way to achieve this.

2022-03-26 16:34 UTC, Ferotiq commented
I might try this later.

2022-03-26 16:34 UTC, closed without merging