Convert UserDAO to typescript
Miodec/monkeytype pull request #2821
Opened 2022-04-09 12:08 UTC by rizwanmustafa

Needs alot of fixes

2022-04-09 12:25 UTC, rizwanmustafa commented
@Bruception @Miodec A review please.

2022-04-09 14:40 UTC, Bruception commented on backend/dao/user.ts
> +    } else {
Useless else

2022-04-09 14:40 UTC, Bruception commented on backend/dao/user.ts
> +    } else {
Useless else

2022-04-09 14:41 UTC, Bruception commented on backend/dao/user.ts
> +    } else {
Useless else

2022-04-09 14:41 UTC, Bruception commented on backend/dao/user.ts
> +    } else {
Useless else

2022-04-09 14:42 UTC, Bruception commented on backend/utils/pb.ts
> +  LbPersonalBests?: MonkeyTypes.LbPersonalBests;
Why is first letter capital?

2022-04-09 14:44 UTC, Bruception commented on backend/dao/user.ts
> +class UsersDAO {
Might as well remove class syntax while you are at it.

2022-04-09 16:54 UTC, rizwanmustafa commented
@Miodec  @Bruception A final review please. Thanks

2022-04-09 16:54 UTC, rizwanmustafa commented
@Miodec  @Bruception A final review please. Thanks

2022-04-10 19:39 UTC, Bruception approved these changes
Let’s move from dao to something else. Since DAO is not the pattern we are using.

2022-04-10 19:39 UTC, Bruception requested changes
.

2022-04-11 13:54 UTC, rizwanmustafa commented on backend/utils/pb.ts
>    };
I replaced it through VScode so it should be fine.

2022-04-13 11:55 UTC, Miodec requested changes
Lets make a new folder `/dal/` and move the converted dao's there

2022-04-13 13:36 UTC, Miodec approved these changes

2022-04-14 16:07 UTC, Miodec approved these changes

2022-04-14 16:07 UTC, merged