(Backend) Ability to make Quotes Favorite
Miodec/monkeytype pull request #2826
Opened 2022-04-10 02:41 UTC by rizwanmustafa

### Description

Closes #

2022-04-10 19:30 UTC, Bruception commented on backend/api/routes/users.ts
> +  "/favQuotes",
favoriteQuotes

2022-04-11 16:34 UTC, Miodec requested changes
Lets add a limit of 100 favorite quotes

2022-04-12 10:10 UTC, rizwanmustafa commented
> Lets add a limit of 100 favorite quotes

Done

2022-04-12 13:29 UTC, Bruception commented on backend/api/routes/quotes.ts
> +const router = Router();
Why did you change this?

2022-04-12 13:47 UTC, Bruception commented on backend/api/controllers/user.ts
> +    return new MonkeyResponse("Too many favorite quotes", null, 400);
Prefer to throw a MonkeyError here

2022-04-12 13:48 UTC, Bruception commented on backend/api/routes/quotes.ts
> +      language: joi.string().required(),
This schema is repeated. Consider storing it in a variable and reusing it.

2022-04-12 13:48 UTC, Bruception commented on backend/dao/user.js
> +        quotesLength += user.favoriteQuotes[lang].length;
This can be refactored. Try _.sumBy

2022-04-12 13:51 UTC, Bruception commented on backend/dao/user.js
> +    const user = await db.collection("users").findOne({ uid });
Db.collection(“users”) is invoked twice. Consider storing it in a variable.

2022-04-12 13:52 UTC, Bruception commented on backend/dao/user.js
> +    if (!user) {
Repetitive check. Consider making a function that checks if a user exists. Although there might be a better way…

2022-04-12 13:52 UTC, Bruception commented on backend/api/routes/quotes.ts
> +        .regex(/[0-9]+/)
Simpler Regex: \d+

2022-04-12 13:55 UTC, Bruception commented on backend/dao/user.js
> +      if (quotesLength >= 100) return false;
Consider making this amount a configuration.

2022-04-12 14:59 UTC, rizwanmustafa commented on backend/dao/user.js
> +    if (!user) {
I am thinking of creating a function and using it directly below the `authenticateRequest` when we create the route. What do you say?

2022-04-12 15:21 UTC, Bruception commented on backend/constants/base-configuration.ts
> +  maxFavoriteQuotes: 100,
Follow the pattern of the other configuration points.

2022-04-12 15:23 UTC, Bruception commented on backend/dao/user.js
> +    const user = await db.collection("users").findOne({ uid });
Invoking this twice consider variable.

2022-04-12 15:29 UTC, Bruception commented on backend/constants/base-configuration.ts
> +    max: 100,
Max what?

2022-04-13 01:29 UTC, Bruception commented on backend/dao/user.js
> +      throw new MonkeyError(409, "User not found", "getFavoriteQuotes");
Is this check needed? `user?.favoriteQuotes` should be fine

2022-04-13 01:32 UTC, Bruception commented on backend/dao/user.js
> +      return true;
Why does this function return anything? I think making it's return type void is the way.

2022-04-13 01:32 UTC, Bruception commented on backend/dao/user.js
> +    if (!user) {
We should wrap this check with a function that will throw an error.

2022-04-13 01:35 UTC, Bruception commented on backend/dao/user.js
> +    return await usersCollection.updateOne(
Why is this function returning anything?

2022-04-13 01:35 UTC, Bruception commented on backend/dao/user.js
> +  static async addFavoriteQuote(uid, language, quoteId, maxQuotes) {
Fix the weird return types of this function(shouldn't return anything)

2022-04-13 12:16 UTC, rizwanmustafa commented on backend/dao/user.js
> +    if (!user) {
Will do that in a separate PR

2022-04-14 18:14 UTC, Bruception commented on backend/api/routes/users.ts
> +  "/favoriteQuotes",
We should move this back to the quotes routes. Despite storing them in the users collection.

2022-04-14 18:16 UTC, Bruception commented on backend/dao/user.ts
> +  if (!user) {
Still aren’t wrapping this in a function

2022-04-14 18:18 UTC, rizwanmustafa commented on backend/api/routes/users.ts
> +  "/favoriteQuotes",
Miodec asked me to have this is in the users routes

2022-04-14 18:30 UTC, Miodec commented on backend/dao/user.ts
> +  if (!user) {
Separate pr

2022-04-14 18:32 UTC, Miodec approved these changes
Good to me

2022-04-14 20:53 UTC, merged