Changes to add new language - Azerbaijani
Miodec/monkeytype pull request #2839
Opened 2022-04-16 17:44 UTC by woosal1337

### Description

PR contains changes to add new language - Azerbaijani

2022-04-18 19:36 UTC, Ferotiq approved these changes

2022-04-19 11:31 UTC, Miodec requested changes

2022-04-19 11:31 UTC, Miodec commented on frontend/static/languages/_groups.json
> +  },
Please move the group lower. Groups are ordered roughly by the number of native speakers.

2022-04-20 00:00 UTC, woosal1337 commented on frontend/static/languages/_groups.json
> +  },
I am sorry, @Miodec , but I doubt I have got you right. Could you elaborate on what you mean exactly?

2022-04-20 10:40 UTC, Miodec commented on frontend/static/languages/_groups.json
> +  },
Currently, this new group is right under english. Just move it lower in the file

2022-04-20 10:52 UTC, woosal1337 commented on frontend/static/languages/_groups.json
> +  },
> Currently, this new group is right under english. Just move it lower in the file

Alright, @Miodec, I have moved it down under Belarusian. I hope everything should be fine now.

2022-04-20 11:49 UTC, Miodec approved these changes
Thanks

2022-04-20 11:49 UTC, merged