Create romanian
Miodec/monkeytype pull request #2846
Opened 2022-04-20 04:30 UTC by DKparadox

### Description

Closes #

2022-04-20 10:39 UTC, Miodec requested changes
The file is missing the `.json` extension. Please add it.

2022-04-20 19:36 UTC, Miodec requested changes
Please rename the file to just `romanian.json`

2022-04-21 03:28 UTC, Ferotiq commented
You still have a file just called `romanian`. Please delete

2022-04-21 07:17 UTC, DKparadox commented
> You still have a file just called `romanian`. Please delete

did it

2022-04-21 10:26 UTC, Miodec commented on frontend/static/quotes/romanian.json
> +      "text": "Trecutul trebuie s? r?m?n?, ?n vie?ile noastre, la fel de plin de posibilit??i ca viitorul.",
Are the question marks supposed to be there?

2022-04-21 11:20 UTC, DKparadox commented on frontend/static/quotes/romanian.json
> +      "text": "Trecutul trebuie s? r?m?n?, ?n vie?ile noastre, la fel de plin de posibilit??i ca viitorul.",
No. There were symbols like "ă", "â", "ș" and "ț". I suppose they have changed to question mark when I converted the file to .json .

2022-04-21 11:29 UTC, Miodec commented on frontend/static/quotes/romanian.json
> +      "text": "Trecutul trebuie s? r?m?n?, ?n vie?ile noastre, la fel de plin de posibilit??i ca viitorul.",
Go ahead and add those back then.

2022-04-21 11:29 UTC, Miodec approved these changes

2022-04-21 11:32 UTC, merged