impr(backend): report feedback to user about accepted and rejected reports (sanidhyas3s)
Miodec/monkeytype pull request #5298
Opened 2024-04-10 09:39 UTC by sanidhyas3s

### Description
Add two admin endpoints which handle accepted and rejected reports and send mail to user accordingly.

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #3909

2024-04-12 07:54 UTC, Miodec requested changes

2024-04-12 07:54 UTC, Miodec commented on backend/src/api/controllers/admin.ts
> +const COLLECTION_NAME = "reports";
I wouldnt store this like that since we will have more functions here which might use a different collection name.

2024-04-12 07:54 UTC, Miodec commented on backend/src/api/controllers/admin.ts
> +    console.log("code added");
console log

2024-04-12 07:54 UTC, Miodec commented on backend/src/api/controllers/admin.ts
> +      if (verdict === true) {
We dont need a verdict boolean if we have a separate accept and deny endpoints.

2024-04-12 07:54 UTC, Miodec commented on backend/src/api/controllers/admin.ts
> +      if (verdict === false) {
Same here, we don't need a verdict.

2024-04-12 07:59 UTC, sanidhyas3s commented on backend/src/api/controllers/admin.ts
> +      if (verdict === false) {
so we just send accepted reports to the accepted endpoint and rejected to the rejected. will make the changes accordingly.

2024-04-12 08:56 UTC, fehmer commented on backend/src/api/controllers/admin.ts
> +    for (const { reportId } of reports) {
While performance does not matter much on this endpoint i'd still reduce the amount of calls to the db and fetch all reports in one call.

2024-04-12 08:58 UTC, fehmer commented on backend/src/api/controllers/admin.ts
> +    for (const { reportId, reason } of reports) {
a lot of duplicated code between the two functions, i'd add a third method with parameters `accepted:boolean, reportIds: number[]`

2024-04-12 09:02 UTC, fehmer commented on backend/src/api/controllers/admin.ts
> +      if (!report) {
not sure about the error handling here. If the request has three Ids with the first and the last one existing and the second one non existing you'll get a 404 response but the first Id will be handled. The caller has no indication why the request failed (error message doesn't contain the reportId which is non existing).

We could either ignore missing reportIds or should fail the call without modifing any report if there is one non-existing reportId in the request.

2024-04-12 09:07 UTC, fehmer commented on backend/src/api/controllers/admin.ts
> +const REPORTS_COLLECTION = "reports";
should we follow the structure of the other endpoints and move the db related code to the `dal` layer?

2024-04-12 09:08 UTC, sanidhyas3s commented on backend/src/api/controllers/admin.ts
> +      if (!report) {
Yeah, I see the problem, will fix it. Making the entire request atomic in way, going through with all or failing all.

2024-04-12 09:08 UTC, fehmer commented on backend/src/api/controllers/admin.ts
> +async function removeReportFromDb(reportId: string): Promise<void> {
should we accept an array of ids?

2024-04-12 09:08 UTC, sanidhyas3s commented on backend/src/api/controllers/admin.ts
> +const REPORTS_COLLECTION = "reports";
was thinking about that too, I think we can, I'll do it

2024-04-12 09:11 UTC, fehmer commented on backend/src/api/controllers/admin.ts
> +  if (result.deletedCount === 0) {
we send out the email before calling this function so the user will get a successful email while the report was not deleted.

2024-04-12 09:13 UTC, fehmer commented on backend/src/api/controllers/admin.ts
> +      const query = { _id: new ObjectId(reportId) };
do we query by `report.uid` or `report._id` @Miodec ?

2024-04-12 17:31 UTC, fehmer commented on backend/src/api/controllers/admin.ts
> +  // sorting both the arrays ensures one to one mapping as no reports are missing
unusual approach. What about storing the reportsFromDb in a map?
`const reportById = new Map( reportsFromDb.map((it) => [it.id, it]));`

and in the loop `reportById.get(report.id);`

2024-04-12 17:37 UTC, sanidhyas3s commented on backend/src/api/controllers/admin.ts
> +  // sorting both the arrays ensures one to one mapping as no reports are missing
Yeah, that seems better. Will change it.

2024-04-13 00:11 UTC, fehmer submitted a review, later dismissed
nice work

2024-04-21 04:06 UTC, sanidhyas3s commented
@Miodec can you merge this or anything left to do?

2024-04-23 09:31 UTC, Miodec commented on backend/src/api/routes/admin.ts
> +            reason: joi.string().optional(),
Move reason to the reject endpoint

2024-04-23 09:40 UTC, sanidhyas3s commented on backend/src/api/routes/admin.ts
> +            reason: joi.string().optional(),
I have kept it this way to keep the accept and reject endpoints consistent and also enabling better reuse of code. Anyway the reason parameter is optional and hence the accept endpoint can be used completely without it.

2024-04-23 09:54 UTC, merged

2024-04-23 09:54 UTC, Miodec commented
Thanks