Monkey type avi123nash
Miodec/monkeytype pull request #860
Opened 2021-01-19 11:22 UTC by avi123nash

Adding a language or a theme? No

Duration was not being passed to error notification which is why it'll stay for infinite time and needs to be closed manually

If your change is visual (mainly themes) it would be extra awesome if you could include a screenshot.
<img width="960" alt="error_notif" src="https://user-images.githubusercontent.com/14849738/105028114-9fe29700-5a76-11eb-8127-827fd5c3afab.png">

2021-01-20 07:53 UTC, avi123nash commented
@Miodec Please review

2021-01-20 16:56 UTC, Miodec commented
Im not exactly sure whats this meant to do

2021-01-20 16:57 UTC, Miodec requested changes

2021-01-20 16:57 UTC, Miodec commented on src/sass/style.scss
> +  right: 12rem;
Why this change?

2021-01-20 16:57 UTC, Miodec commented on src/js/leaderboards.js
> +      Notifications.add("Something went wrong: " + e.message, -1, 3);
Errors are supposed to have no duration, so that they stay on screen.

2021-01-21 06:11 UTC, avi123nash commented on src/sass/style.scss
> +  right: 12rem;
Reverted it back. I tested in local the error message was going out of screen but when I checked the actual website the error message was correct. My Bad

2021-01-21 06:12 UTC, avi123nash commented on src/js/leaderboards.js
> +      Notifications.add("Something went wrong: " + e.message, -1, 3);
Reverting this change too. Thanks

2021-01-21 16:25 UTC, merged